### ISSUE TITLE
Add the policy evaluation results in the tracing data of the policies running in monitor mode

### ISSUE THREAD

**Issue by jvanz** [kubewarden/policy-server#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While I was working in the [issue 260](https://github.com/kubewarden/policy-server/issues/260) I wondered if we should not change where we send the traces to Jaeger. Or at least, add other fields in the traces. [The traces sending to Jaeger happen after the ](https://github.com/kubewarden/policy-server/blob/main/src/worker.rs#L245-L290)`validation_response_with_constraints`[ call](https://github.com/kubewarden/policy-server/blob/main/src/worker.rs#L245-L290). This means that we lost the information about the actual policy evaluation.  In the end, we will always get accepted requests traces in the Jaeger. But we do not know if the request would be reject in the protected mode and the reason of that.

### Expected Behavior

The user should be able to see the actual policy evaluation results in the traces of policies running in monitor mode

### Environment

```markdown
Any
```

**Comment by jvanz** [comment]
Furthermore, I think we should decoder the patch created by the mutating policies in monitor mode and add it in the jaeger entry. This away, user can check how the mutating policies will work in protect mode.

**Comment by flavio** [comment]
I think we have a problem, if I understand the code correctly...

Let's assume we have a policy that is put in monitor mode, this policy is rejecting a request.

With the current code the validation response is going to be changed by the `Worker::validation_response_with_constraints` function. The validation response will be accept.
A trace event about this change is going to be emitted. When looking at the whole policy evaluation (from the time the request is received, to the final response) this log is going to be shown into the whole evaluation tree.

However, the prometheus metrics are going to be wrong. We will emit a metric that states that this policy in monitor mode has accepted a request (which is the final outcome), but we have lost the critical information for policies in monitor mode: how many requests would be rejected by them.

I think the code has to be changed so that:
  * https://github.com/kubewarden/policy-server/blob/ece48e94bedfa9478720c30a371c7c84bd022466/src/worker.rs#L236-L237 we save the evaluation result into `vanilla_validation_response`
  * `vanilla_validation_response` is taken here instead: https://github.com/kubewarden/policy-server/blob/ece48e94bedfa9478720c30a371c7c84bd022466/src/worker.rs#L248
  * We use `vanilla_validation_response` fields in here: https://github.com/kubewarden/policy-server/blob/ece48e94bedfa9478720c30a371c7c84bd022466/src/worker.rs#L274-L284
