### ISSUE TITLE
Use MsgPack instead of Json to move data back and forth between host and Wasm

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/policy-server#28]
Currently the data exchanged between the policy-server and the wasm "world" is encoded using json. The waPC upstream project instead decided to use [MsgPack](https://msgpack.org) as an encoding format. Their choice doesn't force us to change our approach, however it guarantees that all the languages supported by waPC have also libraries to deal with MsgPack.

# Why should we move to MsgPack?

* MsgPack is an optimized (in terms of size) version of JSON encoding. That would reduce the amount of information sent back and forth between policy-server and Wasm policies. That will hopefully lead to faster evaluation times.

* Support more languages. TinyGO for example, only has limited json support.

**Comment by flavio** [comment]
I think we can close that, I don't see us having the time to work on that on the short time.

Moreover, instead of just using MsgPack, we should investigate the use of [widl](https://wapc.io/docs/#widl), which is something specific to waPC.

> WIDL & the waPC CLI
> 
> Use the WebAssembly Interface Definition Language (WIDL) to define your WebAssembly’s schema and the wapc CLI to generate all the code except your business logic.

This would allow us to define the communication protocol between policy-evaluator and the Wasm modules in a single place, and then have client libraries automatically generated by widl.

Right now we don't plan to change the communication protocol we already have in place -> I don't see a real benefit of moving to widl

**Comment by ereslibre** [comment]
@flavio I haven't looked into the details, but is https://github.com/bytecodealliance/witx-bindgen also another possibility?

**Comment by flavio** [comment]
Yes, that could replace waPC in the future
